---
title: "FDA results - All boxes, missing data omitted"
author: "Madeline Peters, Aaron King"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load required packages

```{r packages}
library(tidyverse)
library(scales)
```

## Set working directory

```{r directory}
setwd("~/Documents/GitHub/bdd/nw11_hier/final_files/")
```

## Colour-blind friendly colour palette

```{r palette}
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

## Load data

```{r data}
##Read in data
read_csv(
  "data.csv",
  col_types="iiinnnn"
) |>
  mutate(
    mouseid=sprintf("%02d-%02d",box,mouse),
    box=sprintf("%02d",box),
    mouse=sprintf("%02d",mouse),
    paba=as.factor(box),
    rbc_density=rbc_density/1000,
    pABA=case_match(
      paba,
    "01"~"5%",
    "02"~"0.5%",
    "03"~"0.05%",
    "04"~"0%",
    "05"~"Control"
    )
  ) |>
  select(
    day,
    mouseid,
    pABA,
    box,
    mouse,
    Pd=ama_density,
    RBC=rbc_density,
    Ter119=ter119_density,
    CD71=cd71_density
  ) |>
  arrange(mouseid,day) |>
  mutate(
    pABA=as.character(pABA),
    Ter119=if_else(Ter119==0,NA_real_,Ter119),
    CD71=if_else(CD71==0,NA_real_,CD71),
    Eryth=(1-CD71/Ter119)*RBC,
    Retic=CD71/Ter119*RBC,
    Mouse=case_when(
      mouse=="01"~"A",
      mouse=="02"~"B",
      mouse=="03"~"C",
      TRUE~NA_character_
    )
  ) -> data_full
data_full$pABA <- factor(data_full$pABA,levels=c("Control","0%","0.05%","0.5%","5%"))
data_full$Pd[data_full$box=="05"] <- NA
```

## Load fits

```{r fits}
coef_df <- read_csv("parameter_results_FullModel.csv",show_col_types = FALSE)
po_df <- read_csv("trajectory_results_FullModel.csv",show_col_types = FALSE) |>
  mutate(
  pABA=case_match(
    box,
    "01"~"5%",
    "02"~"0.5%",
    "03"~"0.05%",
    "04"~"0%",
    "05"~"Control"
  ),
  name=case_match(
    name,
    "logE"~"Erythrocytes",
    "logR"~"Reticulocytes",
    "logM"~"Merozoites",
    "logN"~"Indiscriminate killing",
    "logW"~"Targeted killing",
    "logK"~"Parasites"
  )) |>
  select(name,Mouse=mouse,value,time,box,pABA)
po_df$Mouse[po_df$Mouse=="GROUP"] = "Group"
po_df$pABA <- factor(po_df$pABA,levels=c("Control","0%","0.05%","0.5%","5%"))
po_df$name <- factor(po_df$name, levels=c("Parasites","Merozoites","Erythrocytes","Reticulocytes","Indiscriminate killing","Targeted killing"))
```

## Parameter estimates

```{r fits}
coef_df |> select(-box) |> unique()
```

## Plot model results

```{r results}
po_df |> pivot_wider(names_from=name,values_from=value) |>
  mutate(RBC=Erythrocytes+Reticulocytes) |>
  select(Mouse,time,box,pABA,Reticulocytes,`Indiscriminate killing`,
         `Targeted killing`,RBC) |>
  pivot_longer(-c(Mouse,time,box,pABA)) -> po_tmp

po_tmp|>
  ggplot(aes(x=time,y=value,color=Mouse,linewidth=Mouse=="Group"))+
  geom_line()+
  scale_linewidth_manual(guide="none",values=c(`TRUE`=2,`FALSE`=1))+
  scale_colour_manual(values=cbPalette)+
  scale_y_log10()+
  xlab("Days")+ylab("Density per microlitre")+
  facet_grid(name~pABA,scales="free_y")+
  theme_bw()+
  theme(
    strip.background = element_blank()
  )
```

## Compare model results to data

```{r comparison}
po_df |>
  filter(Mouse!="Group",name%in%c("Erythrocytes","Reticulocytes","Merozoites")) |>
  pivot_wider(names_from=name,values_from=value) |>
  mutate(Parasites=(Reticulocytes+Erythrocytes)*(1-exp(-Merozoites/(Reticulocytes+Erythrocytes))),
         RBC=Reticulocytes+Erythrocytes) |>
  select(time,Mouse,box,pABA,RBC,Reticulocytes,Parasites,Erythrocytes) |>
  unite("ID",c(time,box,Mouse),sep="_",remove=F) -> fits

data_full |>
  select(time=day,pABA,box,Mouse,Parasites=Pd,RBC,Reticulocytes=Retic,Erythrocytes=Eryth) |>
  unite("ID",c(time,box,Mouse),sep="_",remove=F) -> data

data <- slice(data,which(data$ID%in%fits$ID))

fits |> pivot_longer(-c(ID,time,Mouse,box,pABA)) -> fits
data |> pivot_longer(-c(ID,time,Mouse,box,pABA)) -> data
  
ggplot()+
  geom_point(data=data,aes(x=time,y=value,col=name))+
  geom_line(data=fits,aes(x=time,y=value,col=name))+
  facet_grid(pABA~Mouse)+
  scale_colour_manual(values=cbPalette)+
  scale_y_log10()+
  xlab("Day")+ylab("Density per microlitre")+
  theme_bw()+
  theme(strip.background=element_blank(),
        legend.title=element_blank(),
        panel.grid = element_blank()
        )
```

## Plot group level time series

```{r group}
po_df |>
  filter(Mouse=="Group") |>
  pivot_wider(names_from=name,values_from=value) |>
  mutate(Parasites=(Reticulocytes+Erythrocytes)*(1-exp(-Merozoites/(Reticulocytes+Erythrocytes))),
         RBC=Reticulocytes+Erythrocytes) |>
  select(time,Mouse,box,pABA,RBC,Erythrocytes,Reticulocytes,Parasites,`Indiscriminate killing`,`Targeted killing`) |>
  pivot_longer(-c(time,Mouse,box,pABA)) -> group_fits

group_fits$name <- factor(group_fits$name,levels=c("RBC","Erythrocytes","Reticulocytes","Indiscriminate killing","Targeted killing","Parasites"))

group_fits |>
  filter(name%in%c("Reticulocytes","Indiscriminate killing","Targeted killing")) |>
  ggplot(aes(x=time,y=value,color=pABA))+
  geom_line(linewidth=2)+
  scale_y_log10()+
  scale_colour_manual(values=cbPalette)+
  xlab("Days")+ylab("Density per microlitre")+
  facet_grid(name~.,scales="free_y")+
  theme_bw()+
  theme(strip.background=element_blank(),
        panel.grid = element_blank()
        )

group_fits |>
  filter(name%in%c("Reticulocytes","Erythrocytes")) |>
  ggplot(aes(x=time,y=value,color=pABA))+
  geom_line(linewidth=2)+
  scale_y_log10()+
  scale_colour_manual(values=cbPalette)+
  xlab("Days")+ylab("Density per microlitre")+
  facet_grid(.~name,scales="free_y")+
  theme_bw()+
  theme(strip.background=element_blank(),
        panel.grid = element_blank()
        )

group_fits |> filter(pABA%in%c("0%"),name%in%c("Parasites")) -> tmp
peak.day <- tmp$time[which(tmp$value==max(tmp$value))]

group_fits |>
  filter(name%in%c("Reticulocytes","Parasites")) |>
  ggplot(aes(x=time,y=value,color=pABA))+
  geom_line(linewidth=2)+
  geom_vline(xintercept=peak.day,linetype="dashed",col="grey")+
  scale_y_log10()+
  scale_colour_manual(values=cbPalette)+
  xlab("Day")+ylab("Density per microlitre")+
  facet_grid(.~name,scales="free_y")+
  theme_bw()+
  theme(strip.background=element_blank(),
        panel.grid = element_blank()
        )
```

## Plot swirlies

```{r swirlies}
po_df |>
  filter(Mouse=="Group") |>
  pivot_wider(names_from=name,values_from=value) |>
  mutate(Parasites=(Reticulocytes+Erythrocytes)*(1-exp(-Merozoites/(Reticulocytes+Erythrocytes))),
         RBC=Reticulocytes+Erythrocytes) |>
  select(time,Mouse,box,pABA,RBC,Erythrocytes,Reticulocytes,Parasites,`Indiscriminate killing`,`Targeted killing`) -> swirls

swirls |>
  ggplot(aes(x=Parasites,y=`Targeted killing`,color=pABA))+
  geom_path(linewidth=2)+
  geom_text(aes(label=time),col="black",size=5)+
  scale_x_log10()+scale_y_log10()+
  scale_colour_manual(values=cbPalette)+
  xlab("Parasite density")+ylab("Targeted killing")+
  theme_bw()+
  theme(
        panel.grid = element_blank()
        )

swirls |>
  ggplot(aes(x=Reticulocytes,y=`Targeted killing`,color=pABA))+
  geom_path(linewidth=2)+
  geom_text(aes(label=time),col="black",size=5)+
  scale_x_log10()+scale_y_log10()+
  scale_colour_manual(values=cbPalette)+
  xlab("Reticulocyte supply")+ylab("Targeted killing")+
  theme_bw()+
  theme(
        panel.grid = element_blank()
        )

swirls |>
  ggplot(aes(x=Reticulocytes,y=`Indiscriminate killing`,color=pABA))+
  geom_path(linewidth=2)+
  geom_text(aes(label=time),col="black",size=5)+
  scale_x_log10()+scale_y_log10()+
  scale_colour_manual(values=cbPalette)+
  xlab("Reticulocyte supply")+ylab("Indiscriminate killing")+
  theme_bw()+
  theme(
        panel.grid = element_blank()
        )

swirls |>
  ggplot(aes(x=`Targeted killing`,y=`Indiscriminate killing`,color=pABA))+
  geom_path(linewidth=2)+
  geom_text(aes(label=time),col="black",size=5)+
  scale_x_log10()+scale_y_log10()+
  scale_colour_manual(values=cbPalette)+
  xlab("Targeted killing")+ylab("Indiscriminate killing")+
  theme_bw()+
  theme(
        panel.grid = element_blank()
        )
```

## Plot reticulocytes versus erythrocytes

```{r pABA0}
ggplot()+
  geom_path(data=swirls,aes(x=Erythrocytes,y=Reticulocytes,color=pABA),linewidth=2)+
  geom_text(data=swirls,aes(x=Erythrocytes,y=Reticulocytes,label=time),col="black",size=5)+
  xlab("Erythrocytes")+ylab("Reticulocytes")+
  theme_bw()+
  scale_x_log10()+scale_y_log10()+
  scale_colour_manual(values=cbPalette)+
  facet_wrap(pABA~.)+
  theme(
        panel.grid = element_blank(),
        legend.position = "none",
        strip.background = element_blank()
        )

ggplot()+
  geom_path(data=swirls,aes(x=Erythrocytes,y=Reticulocytes,color=pABA),linewidth=2)+
  geom_text(data=swirls,aes(x=Erythrocytes,y=Reticulocytes,label=time),col="black",size=5)+
  xlab("Erythrocytes")+ylab("Reticulocytes")+
  theme_bw()+
  scale_colour_manual(values=cbPalette)+
  facet_wrap(pABA~.)+
  theme(
        panel.grid = element_blank(),
        legend.position = "none",
        strip.background = element_blank()
        )
```